#define BUFFER_ALBEDO COLOR0
#define BUFFER_NORMAL0 COLOR1
#define BUFFER_NORMAL1 COLOR2
#define BUFFER_PHYSICAL COLOR3
#define BUFFER_SHAPE COLOR4
#define BUFFER_PALETTE COLOR5
#define BUFFER_RIMLIGHT COLOR6
#define BUFFER_LIGHTMAP_UV COLOR7