#define BUFFER_ALBEDO COLOR0
#define BUFFER_NORMAL COLOR1
#define BUFFER_PHYSICAL COLOR2
#define BUFFER_SHAPE COLOR3
#define BUFFER_PALETTE COLOR4
#define BUFFER_RIMLIGHT COLOR5
#define BUFFER_LIGHTMAP_UV COLOR6